# Working with NumPy

When you start working with numeric computations, you'll soon start wanting to work with sequence of numbers like in **vectors**, a collection of vectors like in **matrices**, and potentially even higher dimensional structures like **tensors**. 

While you could imagine using **a list** to represent a vector, as in:

In [3]:
v1 = [1, 2, 3]
v2 = [4, 5, 6]

Performing very common vector operations like vector additions and dot products can be cumbersome:

In [4]:
v3 = v1 + v2
print(v3)

[1, 2, 3, 4, 5, 6]


In [6]:
def vector_add(v1, v2):
    v3 = []
    for i in range(len(v1)):
        v3.append(v1[i] + v2[i])
    return v3

In [7]:
vector_add(v1, v2)

[5, 7, 9]

Fortunately, you can get access to a very powerful numeric array library for Python by installing **NumPy** package. If you have used Anaconda distribution, then your Python already comes with **NumPy** installed!

To start using the **NumPy** package, you have to import them:

In [8]:
import numpy as np

# Creating NumPy array

You can convert a list into **a NumPy array** that supports more complex numeric operations:

In [11]:
a = np.array([1, 2, 3])

In [12]:
a

array([1, 2, 3])

In [13]:
b = np.array([4, 5, 6])

Unlike lists, NumPy arrays supports mathematical operations like that for vectors and matrices:

sum of two vectors

In [14]:
a + b

array([5, 7, 9])

dot product

In [15]:
a @ b

32

Above you have created a vector or more specifically a **1-D array**

In [16]:
x = np.array([1, 2, 3, 4, 5])

You can look at an array's dimension with its `ndim` property

In [17]:
x.ndim

1

and get its **shape** with `shape` property

In [18]:
x.shape

(5,)

You can create a **2-D array** by turning a **list of list** into an array.

In [19]:
y = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array

y

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
y.ndim

2

In [21]:
y.shape

(2, 3)

# Functions for creating arrays

While you can enter elemetns of array one-by-one, it is far more common to use one of NumPy's special functions for creating an array.

## Range of integers

Just like `range()` function to create an iterable, ther is `np.arange` that let's you create a sequence of integers as a NumPy array

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [25]:
np.arange(3, 30, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

## Specifying start, ending and number of items

Alternatively, you might want to specify the start and end, and also specify **how many elements** should fit in that range, equally spaced apart:

In [35]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [36]:
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

## Common starting array: `ones`, `zeros`, and `random`

You would often want to start with an array of specified sizes (e.g. 3 x 3 matrix) initialized with 0s, 1s, or perhaps random numbers.

### initialize to 0

In [38]:
np.zeros((3, 3))  # be careful - you pass in a tuple specifying the shape

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### initialize to 1

In [39]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### randomly initialized

In [44]:
np.random.rand(4, 2)  # random number uniformly drawn between 0 and 1

array([[0.02809293, 0.70466471],
       [0.83953768, 0.4526591 ],
       [0.04875668, 0.16977409],
       [0.16652201, 0.9121099 ]])

In [45]:
np.random.randn(4, 2)  # random number drawn from standard normal distribution

array([[-0.34668382, -0.85913772],
       [ 1.35628624,  0.22783007],
       [ 0.13226391, -0.64321576],
       [-0.17357519,  0.5416039 ]])

## Other special matrices: identity matrix and diagonal matrix

On other occasions, you'd want to create an identity matrix (matrix where only diagonal elements are 1s) and diagonal matrix (matrix where only diagonal elements are non-zeros)

In [46]:
np.eye(4)  # 4 x 4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
np.diag([1, 2, 3, 4]) # 4 x 4 matrix with 1, 2, 3, 4 as the diagonal entries

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Reshaping arrays

You can create an array in one shape and then later **reshape** it. This can be a neat trick for creating a higher dimensional array with sequential content:

Create a flat sequential array

In [49]:
x = np.arange(15)

x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Now reshape it into 3 x 5

In [50]:
x.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

We are going to revisit array shape manipulation in much more details later.

# Indexing and slicing arrays

You can index and slice a 1-D array just like you would for a list

In [52]:
a = np.arange(10)

In [53]:
a[0]  # first element

0

In [54]:
a[-1] # last element

9

In [55]:
a[3:8] # slicing

array([3, 4, 5, 6, 7])

In [56]:
a[::-1] # reversing

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

When working with **multidimensional arrays**, you have more choices with indexing:

In [57]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
a[0] # selects the first row

array([0, 1, 2, 3])

In [59]:
a[-1] # selects the last row

array([ 8,  9, 10, 11])

In [63]:
a[:2] # slice first two rows

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [60]:
a[0, 1] # selects row 0, column 1

1

In [61]:
a[2, 2]

10

In [64]:
a[1, :3] # slice first row, first three columns

array([4, 5, 6])

In [66]:
a[:, 2] # get column 2

array([ 2,  6, 10])

# Modifying arrays

Just like list, NumPy arrays are **mutable** - meaning, you can change its content after the creation.

In [68]:
x = np.zeros((3, 5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Change one element at a time

In [69]:
x[1, 2] = 3

In [70]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Change an entire row:

In [71]:
x[0] = 4

In [72]:
x

array([[4., 4., 4., 4., 4.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Change an entire column:

In [73]:
x[:, -1] = 5

In [74]:
x

array([[4., 4., 4., 4., 5.],
       [0., 0., 3., 0., 5.],
       [0., 0., 0., 0., 5.]])

## Placing another list into an array

In [75]:
x[-1] = [10, 20, 30, 40, 50]

In [76]:
x

array([[ 4.,  4.,  4.,  4.,  5.],
       [ 0.,  0.,  3.,  0.,  5.],
       [10., 20., 30., 40., 50.]])

In [77]:
x[0] = [1, 2, 3]

ValueError: cannot copy sequence with size 3 to array axis with dimension 5

# Working with arrays

## Elementwise operations

You can perform **elementwise** operations easily with NumPy array

In [79]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [80]:
x + 3

array([3, 4, 5, 6, 7])

In [81]:
x**2

array([ 0,  1,  4,  9, 16])

In [88]:
y = np.ones(5) + 5
y

array([6., 6., 6., 6., 6.])

In [89]:
x - y

array([-6., -5., -4., -3., -2.])

In [94]:
2 ** x

array([ 1,  2,  4,  8, 16])

In [95]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

### Multiplying arrays

When you multiply arrays, they do **not** perform matrix multiplication

In [91]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 0], [0, 1]])

In [92]:
a * b

array([[1, 0],
       [0, 4]])

To get matrix multiplcation, you want to use `@` operator

In [93]:
a @ b

array([[1, 2],
       [3, 4]])